### ISSUE TITLE
Delphi 12.2 Warning: W1075 Overloading a similar index type by declaring an array property 'Items'

### ISSUE THREAD

**Issue by zedxxx** [remobjects/pascalscript#272]
https://github.com/remobjects/pascalscript/blob/master/Source/uPSRuntime.pas#L859
```
[dcc32 Warning] uPSRuntime.pas(857): W1075 Overloading a similar index type by declaring an array property 'Items'
  uPSRuntime.pas(857): Related member: property TPSStack.Items[LongInt]: PPSVariant;
  uPSRuntime.pas(857): Related member: property TPSList.Items[Cardinal]: Pointer;
```

Perhaps `TPSList` can also be switched to the `Longint` type to avoid this warning?

```pascal
  TPSList = class(TObject)
  protected

    FData: PPointerList;

    FCapacity: Cardinal;

    FCount: Cardinal;

    FCheckCount: Cardinal;
  private
    function GetItem(Nr: Cardinal): Pointer;
    procedure SetItem(Nr: Cardinal; P: Pointer);
```
https://github.com/remobjects/pascalscript/blob/master/Source/uPSUtils.pas#L343

**Comment by zedxxx** [comment]
@evgenyk2 Can you please cherry pick these changes into the stable branch?

**Comment by evgenyk2** [comment]
why you dislike master branch?

**Comment by zedxxx** [comment]
Because of #241

**Comment by zedxxx** [comment]
Hm, I just repeated my test with the latest master branch and it seems that the bag has somehow been fixed. I need to do more tests to be sure everything is working properly.

**Comment by zedxxx** [comment]
No, `array of const` still doesn't work with `AnsiString` param. See explanation in #241

**Comment by evgenyk2** [comment]
#241 is fixed

**Comment by zedxxx** [comment]
@evgenyk2 Thank you. But the `master` branch is still broken for me. I can't show a reproducible test right now, but something is definitely wrong with it.
